Algoritmo "Dia da semana"

Var
   dia : inteiro
Inicio
   escreval("Digite o dia em número:")
   leia(dia)
   escolha dia //eq a variavel da escolha a ser comparada
Caso 1
   escreval("Domingo") // eq: se igualdade (var = valor) entao
Caso 2
   escreval("Segunda")
Caso 3
   escreval("Terça")
Caso 4
   escreval("Quarta")
caso 5
   escreval("Quinta")
caso 6
   escreval("Sexta")
caso 7
   escreval("Sábado")
outrocaso // eq: equivalente ao ultimo senão
caso 8
   escreval("Inválido!")
fimescolha



Fimalgoritmo